# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 02:56
from __future__ import unicode_literals

import cmdb.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppVariables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, validators=[cmdb.models.varildate_var])),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '\u5e94\u7528\u53d8\u91cf\u8868',
                'verbose_name_plural': '\u5e94\u7528\u53d8\u91cf\u8868',
            },
        ),
        migrations.CreateModel(
            name='DbBaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('db_charset', models.PositiveIntegerField(choices=[(1, 'AMERICAN_AMERICA.ZHS16GBK'), (2, 'NLS_LANG=AMERICAN_AMERICA.UTF8 ')], default=2)),
            ],
            options={
                'verbose_name': '\u6570\u636e\u5e93\u4fe1\u606f',
                'verbose_name_plural': '\u6570\u636e\u5e93\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='DbVariables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True, validators=[cmdb.models.varildate_var], verbose_name='\u6570\u636e\u5e93key')),
                ('value', models.CharField(max_length=255, verbose_name='\u6570\u636e\u5e93value')),
            ],
            options={
                'verbose_name': '\u6570\u636e\u5e93\u53d8\u91cf\u8868',
                'verbose_name_plural': '\u6570\u636e\u5e93\u53d8\u91cf\u8868',
            },
        ),
        migrations.CreateModel(
            name='EmailList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': '\u90ae\u4ef6\u5730\u5740',
                'verbose_name_plural': '\u90ae\u4ef6\u5730\u5740',
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment_name', models.CharField(max_length=50, unique=True, verbose_name='\u73af\u5883\u540d')),
            ],
            options={
                'verbose_name': '\u90e8\u7f72\u73af\u5883',
                'verbose_name_plural': '\u90e8\u7f72\u73af\u5883',
            },
        ),
        migrations.CreateModel(
            name='ExecuteSqlLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sql_file_name', models.CharField(max_length=128)),
                ('status', models.IntegerField(choices=[(0, 'successfull'), (1, 'failed')])),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('contents', models.TextField()),
                ('db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.DbBaseInfo')),
            ],
            options={
                'verbose_name': 'sql\u6267\u884c\u65e5\u5fd7\u8bb0\u5f55',
                'verbose_name_plural': 'sql\u6267\u884c\u65e5\u5fd7\u8bb0\u5f55',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Ansible\u7ec4',
                'verbose_name_plural': 'Ansible\u7ec4',
            },
        ),
        migrations.CreateModel(
            name='HostEnvironmentRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_type', models.IntegerField(choices=[(0, 'javaapps'), (1, 'webapps')])),
            ],
            options={
                'verbose_name': '\u7ed1\u5b9a\u5173\u7cfb\u8868',
                'verbose_name_plural': '\u7ed1\u5b9a\u5173\u7cfb\u8868',
            },
        ),
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddr', models.GenericIPAddressField(unique=True)),
                ('host_type', models.IntegerField(choices=[(0, 'app'), (1, 'db')])),
            ],
            options={
                'verbose_name': '\u4e3b\u673a',
                'verbose_name_plural': '\u4e3b\u673a',
            },
        ),
        migrations.CreateModel(
            name='JavaAppFoot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foot_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Java\u5e94\u7528\u670d\u52a1\u540d',
                'verbose_name_plural': 'Java\u5e94\u7528\u670d\u52a1\u540d',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastversion', models.CharField(blank=True, max_length=255, null=True)),
                ('pass_uat_test', models.BooleanField()),
                ('uat_job_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_fun_successful_dir', models.CharField(blank=True, max_length=255, null=True)),
                ('admin_email', models.ManyToManyField(blank=True, related_name='admin_email', to='cmdb.EmailList')),
                ('develop_email', models.ManyToManyField(blank=True, related_name='develop_email', to='cmdb.EmailList')),
                ('test_email', models.ManyToManyField(blank=True, related_name='test_email', to='cmdb.EmailList')),
            ],
            options={
                'verbose_name': '\u9879\u76ee',
                'verbose_name_plural': '\u9879\u76ee',
            },
        ),
        migrations.CreateModel(
            name='SvnPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('svn_charset', models.PositiveIntegerField(choices=[(1, 'zh_CN.GB18030'), (2, 'en_US.UTF-8')], default=2)),
            ],
            options={
                'verbose_name': 'svn\u8def\u5f84',
                'verbose_name_plural': 'svn\u8def\u5f84',
            },
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': '\u81ea\u5b9a\u4e49\u914d\u7f6e\u6a21\u7248',
                'verbose_name_plural': '\u81ea\u5b9a\u4e49\u914d\u7f6e\u6a21\u7248',
            },
        ),
        migrations.CreateModel(
            name='Tomcat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('http_type', models.IntegerField(choices=[(0, 'http'), (1, 'https')])),
                ('shutdown_port', models.PositiveIntegerField()),
                ('http_port', models.PositiveIntegerField()),
                ('https_port', models.PositiveIntegerField()),
                ('jvm_size', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Tomcat\u914d\u7f6e',
                'verbose_name_plural': 'Tomcat\u914d\u7f6e',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '\u7248\u672c',
                'verbose_name_plural': '\u7248\u672c',
            },
        ),
        migrations.AlterUniqueTogether(
            name='tomcat',
            unique_together=set([('name', 'http_type', 'shutdown_port', 'http_port', 'https_port')]),
        ),
        migrations.AddField(
            model_name='project',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version', to='cmdb.Version'),
        ),
        migrations.AddField(
            model_name='hostenvironmentrelation',
            name='app_foot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.JavaAppFoot'),
        ),
        migrations.AddField(
            model_name='hostenvironmentrelation',
            name='app_variables',
            field=models.ManyToManyField(blank=True, related_name='en_r_app_var_set', to='cmdb.AppVariables'),
        ),
        migrations.AddField(
            model_name='hostenvironmentrelation',
            name='db_variables',
            field=models.ManyToManyField(blank=True, related_name='en_r_db_var_set', to='cmdb.DbVariables'),
        ),
        migrations.AddField(
            model_name='hostenvironmentrelation',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Environment'),
        ),
        migrations.AddField(
            model_name='hostenvironmentrelation',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Group'),
        ),
        migrations.AddField(
            model_name='hostenvironmentrelation',
            name='hosts',
            field=models.ManyToManyField(to='cmdb.Hosts'),
        ),
        migrations.AddField(
            model_name='hostenvironmentrelation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Project'),
        ),
        migrations.AddField(
            model_name='hostenvironmentrelation',
            name='templates',
            field=models.ManyToManyField(blank=True, to='cmdb.Templates'),
        ),
        migrations.AddField(
            model_name='hostenvironmentrelation',
            name='tomcat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Tomcat'),
        ),
        migrations.AddField(
            model_name='executesqllog',
            name='svn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.SvnPath'),
        ),
    ]
