# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 02:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='executesqllog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='environment',
            name='app_variables',
            field=models.ManyToManyField(blank=True, related_name='en_app_var_set', to='cmdb.AppVariables'),
        ),
        migrations.AddField(
            model_name='environment',
            name='db_variables',
            field=models.ManyToManyField(blank=True, related_name='en_db_var_set', to='cmdb.DbVariables', verbose_name='\u6570\u636e\u5e93\u53d8\u91cf'),
        ),
        migrations.AddField(
            model_name='dbbaseinfo',
            name='db_password',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='db_password_set', to='cmdb.DbVariables'),
        ),
        migrations.AddField(
            model_name='dbbaseinfo',
            name='db_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='db_user_set', to='cmdb.DbVariables'),
        ),
        migrations.AddField(
            model_name='dbbaseinfo',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_set', to='cmdb.DbVariables'),
        ),
        migrations.AddField(
            model_name='dbbaseinfo',
            name='port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_set', to='cmdb.DbVariables'),
        ),
        migrations.AddField(
            model_name='dbbaseinfo',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sid_set', to='cmdb.DbVariables'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set([('name', 'version')]),
        ),
        migrations.AlterUniqueTogether(
            name='hostenvironmentrelation',
            unique_together=set([('environment', 'group', 'project', 'app_foot', 'group_type')]),
        ),
    ]
