# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20170731_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='fun_job_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dbbaseinfo',
            name='db_charset',
            field=models.PositiveIntegerField(choices=[(1, 'AMERICAN_AMERICA.ZHS16GBK'), (2, 'AMERICAN_AMERICA.UTF8 ')], default=2),
        ),
    ]
