# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-17 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_project_production_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appvariables',
            name='key',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
