# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-17 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0006_auto_20171017_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillist',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
