# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 02:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=256, verbose_name='\u8bc1\u4e66\u540d\u79f0')),
                ('cperiod', models.CharField(max_length=32, verbose_name='\u8bc1\u4e66\u6709\u6548\u5468\u671f')),
                ('cexpired_date', models.DateField(verbose_name='\u8bc1\u4e66\u6709\u6548\u671f')),
                ('cprovider', models.CharField(max_length=256, verbose_name='\u8bc1\u4e66\u63d0\u4f9b\u65b9')),
                ('public_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u9881\u53d1\u7684\u516c\u7528\u540d')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('begin_notify_time', models.DateField(blank=True, null=True, verbose_name='\u5f00\u59cb\u63d0\u9192\u65f6\u95f4')),
                ('status', models.BooleanField(verbose_name='\u8bc1\u4e66\u72b6\u6001')),
            ],
            options={
                'verbose_name': '\u8bc1\u4e66',
                'verbose_name_plural': '\u8bc1\u4e66',
            },
        ),
        migrations.CreateModel(
            name='CertificateType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_type_name', models.CharField(max_length=256, verbose_name='\u8bc1\u4e66\u7c7b\u578b\u540d')),
            ],
            options={
                'verbose_name': '\u8bc1\u4e66\u7c7b\u578b',
                'verbose_name_plural': '\u8bc1\u4e66\u7c7b\u578b',
            },
        ),
        migrations.AddField(
            model_name='certificate',
            name='cert_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certmgr.CertificateType', verbose_name='\u8bc1\u4e66\u7c7b\u578b'),
        ),
    ]
