# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 02:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenkinsJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=128, verbose_name='job\u540d\u79f0')),
                ('job_type', models.PositiveIntegerField(choices=[(0, '\u529f\u80fd\u6d4b\u8bd5\u90e8\u7f72(FUN)'), (1, '\u7528\u6237\u9a8c\u6536\u6d4b\u8bd5\u90e8\u7f72(UAT)'), (2, '\u6784\u5efa'), (3, '\u901a\u8fc7\u6d4b\u8bd5'), (4, '\u751f\u4ea7\u51c6\u5907'), (5, '\u53ef\u9009\u7c7b\u578b')], default=2)),
            ],
        ),
        migrations.CreateModel(
            name='JenkinsServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=128)),
                ('ip', models.GenericIPAddressField()),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(blank=True, max_length=256, null=True)),
                ('token', models.CharField(max_length=256)),
                ('api_url', models.URLField()),
                ('workspace', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_name', models.CharField(max_length=128)),
                ('operation_value', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='jenkinsjob',
            name='action_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jenkinsmgr.Operation'),
        ),
        migrations.AddField(
            model_name='jenkinsjob',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Environment'),
        ),
        migrations.AddField(
            model_name='jenkinsjob',
            name='jenkins_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jenkinsmgr.JenkinsServer'),
        ),
        migrations.AddField(
            model_name='jenkinsjob',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Project', verbose_name='\u9879\u76ee\u540d'),
        ),
        migrations.AlterUniqueTogether(
            name='jenkinsjob',
            unique_together=set([('job_name', 'project')]),
        ),
    ]
