# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 01:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jenkinsmgr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jenkinsjob',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_jobs', to='cmdb.Project', verbose_name='\u9879\u76ee\u540d'),
        ),
    ]
