# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jenkinsmgr', '0003_auto_20170815_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jenkinsjob',
            name='job_type',
            field=models.PositiveIntegerField(choices=[(0, '\u529f\u80fd\u6d4b\u8bd5\u90e8\u7f72(FUN)'), (1, '\u7528\u6237\u9a8c\u6536\u6d4b\u8bd5\u90e8\u7f72(UAT)'), (2, '\u6784\u5efa'), (3, '\u901a\u8fc7\u6d4b\u8bd5'), (4, '\u751f\u4ea7\u51c6\u5907'), (5, '\u53ef\u9009\u7c7b\u578b')], default=2),
        ),
        migrations.AlterUniqueTogether(
            name='operation',
            unique_together=set([('operation_name', 'operation_value')]),
        ),
    ]
