# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jenkinsmgr', '0005_auto_20170821_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='jenkinsjob',
            name='auto_build',
            field=models.BooleanField(default=False),
        ),
    ]
