# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-17 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0006_auto_20171017_0830'),
        ('jenkinsmgr', '0006_jenkinsjob_auto_build'),
    ]

    operations = [
        migrations.AddField(
            model_name='jenkinsjob',
            name='emails',
            field=models.ManyToManyField(blank=True, null=True, to='cmdb.EmailList'),
        ),
    ]
