# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-17 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jenkinsmgr', '0007_jenkinsjob_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jenkinsjob',
            name='emails',
            field=models.ManyToManyField(blank=True, to='cmdb.EmailList'),
        ),
    ]
