# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-26 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jenkinsmgr', '0008_auto_20171017_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='jenkinsjob',
            name='svn_url',
            field=models.URLField(null=True),
        ),
    ]
