# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-26 00:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jenkinsmgr', '0009_jenkinsjob_svn_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jenkinsjob',
            name='svn_url',
        ),
    ]
