# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0001_initial'),
        ('jenkinsmgr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='username ')),
                ('alias', models.CharField(blank=True, max_length=64, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('gender', models.PositiveIntegerField(choices=[(0, 'female'), (1, 'male')], default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('jenkins_job', models.ManyToManyField(blank=True, to='jenkinsmgr.JenkinsJob')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '\u7528\u6237',
                'verbose_name_plural': '\u7528\u6237',
                'permissions': (('db_list', '\u53ef\u4ee5\u8bbf\u95ee \u6570\u636e\u5e93\u5217\u8868\u9875'), ('db_execute_sql', '\u6570\u636e\u5e93\u6267\u884csql\u6743\u9650'), ('db_svn_update', '\u66f4\u65b0\u6570\u636e\u5e93\u811a\u672csvn\u76ee\u5f55'), ('deploy_list', '\u90e8\u7f72\u7ba1\u7406'), ('deploy_add', '\u6dfb\u52a0\u90e8\u7f72\u914d\u7f6e'), ('deploy_change', '\u4fee\u6539\u90e8\u7f72\u914d\u7f6e'), ('deploy_delete', '\u5220\u9664\u90e8\u7f72\u914d\u7f6e'), ('cert_list', '\u8bc1\u4e66\u7ba1\u7406'), ('cert_add', '\u6dfb\u52a0\u8bc1\u4e66'), ('cert_change', '\u4fee\u6539\u8bc1\u4e66'), ('cert_delete', '\u5220\u9664\u8bc1\u4e66'), ('releasemgr_list', '\u53d1\u5e03\u8ba1\u5212\u7ba1\u7406'), ('releasemgr_add', '\u6dfb\u52a0\u53d1\u5e03\u8ba1\u5212'), ('releasemgr_change', '\u4fee\u6539\u53d1\u5e03\u8ba1\u5212'), ('releasemgr_delete', '\u5220\u9664\u53d1\u5e03\u8ba1\u5212'), ('jenkins_server_list', 'jenkins\u7ba1\u7406'), ('jenkins_job_detail', 'jenkins job\u64cd\u4f5c'), ('jenkins_admin', 'jenkins\u7ba1\u7406\u5458')),
            },
        ),
    ]
