# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'permissions': (('db_list', '\u53ef\u4ee5\u8bbf\u95ee \u6570\u636e\u5e93\u5217\u8868\u9875'), ('db_execute_sql', '\u6570\u636e\u5e93\u6267\u884csql\u6743\u9650'), ('db_svn_update', '\u66f4\u65b0\u6570\u636e\u5e93\u811a\u672csvn\u76ee\u5f55'), ('deploy_list', '\u90e8\u7f72\u7ba1\u7406'), ('deploy_add', '\u6dfb\u52a0\u90e8\u7f72\u914d\u7f6e'), ('deploy_change', '\u4fee\u6539\u90e8\u7f72\u914d\u7f6e'), ('deploy_delete', '\u5220\u9664\u90e8\u7f72\u914d\u7f6e'), ('cert_list', '\u8bc1\u4e66\u7ba1\u7406'), ('cert_add', '\u6dfb\u52a0\u8bc1\u4e66'), ('cert_change', '\u4fee\u6539\u8bc1\u4e66'), ('cert_delete', '\u5220\u9664\u8bc1\u4e66'), ('releasemgr_list', '\u53d1\u5e03\u8ba1\u5212\u7ba1\u7406'), ('releasemgr_add', '\u6dfb\u52a0\u53d1\u5e03\u8ba1\u5212'), ('releasemgr_change', '\u4fee\u6539\u53d1\u5e03\u8ba1\u5212'), ('releasemgr_delete', '\u5220\u9664\u53d1\u5e03\u8ba1\u5212'), ('jenkins_server_list', 'jenkins\u7ba1\u7406'), ('jenkins_job_detail', 'jenkins job\u64cd\u4f5c'), ('jenkins_admin', 'jenkins\u7ba1\u7406\u5458')), 'verbose_name': '\u7528\u6237', 'verbose_name_plural': '\u7528\u6237'},
        ),
    ]
