# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-17 00:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0002_auto_20170724_1846'),
        ('usercenter', '0002_auto_20170731_1109'),
    ]

    operations = [
    ]
