# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 02:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=256, verbose_name='\u7cfb\u7edf\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u7cfb\u7edf\u540d\u79f0\u914d\u7f6e\u9879',
                'verbose_name_plural': '\u7cfb\u7edf\u540d\u79f0\u914d\u7f6e\u9879',
            },
        ),
        migrations.CreateModel(
            name='ReleasePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='\u53d1\u5e03\u5185\u5bb9')),
                ('release_date', models.DateField(verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('worker', models.CharField(max_length=256, verbose_name='\u5b9e\u65bd\u8d1f\u8d23\u4eba')),
                ('need_validation', models.BooleanField(verbose_name='\u9700\u8981\u9a8c\u8bc1')),
                ('app_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='releasemgr.AppName', verbose_name='\u7cfb\u7edf\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u53d1\u5e03\u8ba1\u5212\u7ba1\u7406',
                'verbose_name_plural': '\u53d1\u5e03\u8ba1\u5212\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='ReleaseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_type', models.CharField(max_length=256, verbose_name='\u53d1\u5e03\u7c7b\u578b')),
            ],
            options={
                'verbose_name': '\u53d1\u5e03\u7c7b\u578b\u914d\u7f6e\u9879',
                'verbose_name_plural': '\u53d1\u5e03\u7c7b\u578b\u914d\u7f6e\u9879',
            },
        ),
        migrations.AddField(
            model_name='releaseplan',
            name='release_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='releasemgr.ReleaseType', verbose_name='\u53d1\u5e03\u7c7b\u578b'),
        ),
    ]
